language: python
python:
  - "3.5"
install:
  - pip install -U tox
env:
  matrix:
    - TESTENV=py27
    - TESTENV=py34
    - TESTENV=py35
    - TESTENV=flake8
    - TESTENV=docs
    - TESTENV=docs_linkcheck
    - TESTENV=doctest
script:
  - tox -r -e $TESTENV
